### ISSUE TITLE
Criar branch 9.5 e 9.5 - dev 

### ISSUE THREAD

**Issue by verdanatech-luana** [verdanatech/archimap#1]
![2021-08-16_12-07](https://user-images.githubusercontent.com/86842154/129586040-0ebc0d05-ac2d-4cfe-87e7-fba4d4f41db0.png)

**Comment by verdanatech-luana** [comment]
Branchs 9.5 e 9.5-dev adicionadas.

![2021-08-16_14-02](https://user-images.githubusercontent.com/86842154/129601945-30934bc5-9367-420c-a27e-6629b365827e.png)

![2021-08-16_14-03](https://user-images.githubusercontent.com/86842154/129601958-bbf97078-d752-4247-8025-e915e0f7154e.png)

**Comment by verdanatech-marcio** [comment]
Testado, plugin funcionando no GLPI - 9.5
![TesteAM](https://user-images.githubusercontent.com/80538863/129726062-ac0a4180-2b40-4d53-8332-2f727e3199c9.png)
